version: '3.8'

services:
  postgres:
    build:
      context: ./docker/postgres
    container_name: postgres-container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    build:
      context: ./docker/mongodb
    container_name: mongodb-container
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
#docker cp "/workspace/mounting/sales_data_sample - sales_data_sample.csv" 51e:/var/lib/postgresql/data/sales2.csv